### PR TITLE
Pull in Serilog's default JSON formatter

### PR DESCRIPTION
**Pull request by nblumhardt**
...to break dependency on Serilog.Formatting.Json.JsonFormatter virtual extension points (serilog/serilog#819)

### CODE REVIEW

**Comment by nblumhardt** [comment]
```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unhandled Exception: GitTools.WarningException: It looks like the branch being examined is a detached Head pointing to commit 'acafa4f'. Without a proper branch name GitVersion cannot determine the build version.
```

It looks like some more work may be required for GitVersion to work for PRs, or perhaps it could just default to some fixed version when in detached head state? CC @mivano

**Comment by nblumhardt** [comment]
Any guidance on this one folks? Never having used GitVersion I'm not sure where to start; would using the versioning scheme from the other Serilog repos help here? (I can PR if so).

**Comment by mivano** [comment]
Hmm that is a nice one. We are using gitversion with TFS builds and never run into this. For PRs (feature branches) it creates nice x.y.z-branchname0001 versions. Which are nuget compatible. Are you aware of an option in Appveyor to tell it to get the branch by its name? Otherwise we need to make it optional for PRs and just use a random version number. But that defeats the nice gitversion way...

**Comment by mivano** [comment]
I checked in to dev an updated build.ps1 file that ignores gitversion when on a head less branch. Can you try and see if this fixes the issue?

**Comment by nblumhardt** [comment]
@mivano :white_check_mark: ready to go!

**Comment by mivano** [comment]
Great, I merged it back to dev.

**Comment by nblumhardt** [comment]
Thanks :+1:

**Pull request merged**
