### PR TITLE
Configure ExceptionAsObjectJsonFormatter via configuration

### PR DESCRIPTION
**Pull request by iss0**
**What issue does this PR address?**
#143

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Comment by mivano** [comment]
Thanks for the PR. Adding parameters, even optional, is breaking the signature. Not a big deal, but something to be aware of. I see what you want to do, but this makes it very specific. Could you not create your own method extension in your project with that specific code, name it ElasticsearchCustom and use that instead for your configuration needs? Now it is linked to this specific formatter using magic strings.

**Comment by iss0** [comment]
You're quiet right about the magic string stuff. It is really not a good way to do it. At least I could've used nameof(ExceptionAsObjectJsonFormatter) in the case.

In general using an extension method in my application to configure the custom formatter means I can not use App.Config or Web.Config to configure the sink at all or can I?

**Comment by mivano** [comment]
I believe the code that populates the config looks for matching method names. So use ElasticsearchCustom in this case as the name of the sink. Not tested this, but might be a path to explore?

**Comment by iss0** [comment]
Oh yes! I did not know that. Sounds like the perfect solution for me. I will have a look if this works for me. Thank you!

**Comment by iss0** [comment]
Just a short heads up. It did actually work quite well. I am able to configure it via my own extension method. Thinks this can be closed for good.

**Comment by mivano** [comment]
Perfect, thanks for the follow up.

**Pull request closed without merging**
