### PR TITLE
Get rid of 'deprecated' warnings in Elastic 5.6.2

### PR DESCRIPTION
**Pull request by VanHuychemG**
Our Elastic 5.6.2 logs are flooded with below errors:
The [string] field is deprecated, please use [text] or [keyword]
[omit_norms] is deprecated, please use [norms] instead with the opposite boolean value

Updated the schema following https://www.elastic.co/blog/strings-are-dead-long-live-strings

### CODE REVIEW

**Comment by CumpsD** [comment]
Looking forward to this, we are seeing the same

**Comment by CumpsD** [comment]
When reading the issues, it seems in ES 6 the deprecation turned into removal, so this PR might fix ES 6 support too :)

**Comment by quetzalcoatl** [comment]
LGTM - but I'm no expert here :) Changes are similar to what I did to patch up the same set of issues for me (see code I provided in comments in issue #129). However, I didn't know about `keyword` type (sadly, I didn't stumble on that strings-are-dead article) so I had to comment out 'ignore_above' as well. Good to know! This piece is obviously much better than mine.

One thing I noticed is that this is just a change to mappings. Since newest ElasticSearch changed the schema (like 'index' is now true/false), then IMHO applying this will break support for lower versions of ElasticSearch. That may be OK, but then, [at least one person was concerned some time ago](https://github.com/serilog/serilog-sinks-elasticsearch/issues/129#issuecomment-351444263)

**Comment by VanHuychemG** [comment]
I'll have a go at creating some kind of template provider, that can be set from the options ,something like pre-version5, version5, version6.

**Comment by CumpsD** [comment]
Awesome! Looking forward to get this merged! // @mivano

**Comment by mivano** [comment]
Thanks for the all the work. I will have a look soon.
Op do 11 jan. 2018 om 13:44 schreef David Cumps <notifications@github.com>

**Comment by mivano** [comment]
Great addition and thanks for the backward capability option!

**Comment by CumpsD** [comment]
Awesome!

**Pull request merged**
