### PR TITLE
Missing {"@ in body #102. ElasticsearchLogShipper has the wrong success criteria for Bulk operations #25

### PR DESCRIPTION
**Pull request by Lanoli**
Enable reading from UTF-8 files with or without BOM.

### CODE REVIEW

**Comment by Lanoli** [comment]
Deserialize bulkresponse & log failed operations

**Comment by mivano** [comment]
You introduce the full NEST library here. We try to stick with the more lightweight Elasticsearch.net library only. Can we do without NEST?

**Comment by Lanoli** [comment]
NEST contains the BulkResponse class which uses BulkResponseItemJsonConverter to deserialize.

**Comment by mivano** [comment]
That is true, but it also introduces a lot of other stuff. You can use a dynamic or parse it yourself without introducing NEST.

**Comment by Lanoli** [comment]
I mailndy used NEST because I don't know the responsetypes of all the different elasticsearch versions. This way you get a battletested, maintained deserialisation.  Copying these classes over to this project is an option to make it more lighteweight.

**Comment by mivano** [comment]
See here (https://github.com/serilog/serilog-sinks-elasticsearch/blob/handlefailures/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs#L60) for a way to parse without the NEST dependency. We would like to stick with the low level elasticsearch.net library as much as possible.

**Comment by Lanoli** [comment]
Why not copy the Bulkresponse and jsonconverter from NEST over to this project ? Those are well tested and used by the community.

**Comment by Lanoli** [comment]
I removed NEST and changed the parsing to use dynamics + merge with DEV.

**Comment by lrolsen** [comment]
@Lanoli  Are there any plans to get these changes into master?

**Comment by Lanoli** [comment]
@mivano ,

**Comment by olegKoshmeliuk** [comment]
@mivano any chance to have such feature merged into master?
I have few point how to improve this PR.
1. remove custom created id in at sink, since items array order is same as request items (https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html)
2. Add same code for not durable sink
3. expose error event to user code via callback or event (in ElasticsearchSinkOptions). This will helpul if you have mapping errors ( like "failed to parse [fields.LogId]" expected string got object). so users can log them back into elasticsearch.

If you don't mind i can create pull requests with my changes.

**Comment by mivano** [comment]
I merged your changes and dev into this branch: https://github.com/serilog/serilog-sinks-elasticsearch/tree/Lanoli-dev
I also added some other improvements that should help with error detection and recovery. I m not completely satisfied with it yet, so please have a look. 

I also added a sample project and a docker compose file to set up an environment.

Regarding your points:
 1. Yes I think that is not needed, see also my implementation in https://github.com/serilog/serilog-sinks-elasticsearch/blob/0c9bdd35e2aa475b4c84ca1cd7d4286c4c6be76a/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticSearchSink.cs#L63
 2. Although I like the ability for the durable sink, it adds duplication which should not be there.
 3. I added this option: https://github.com/serilog/serilog-sinks-elasticsearch/blob/0c9bdd35e2aa475b4c84ca1cd7d4286c4c6be76a/src/Serilog.Sinks.Elasticsearch/Sinks/ElasticSearch/ElasticsearchSinkOptions.cs#L236-L252 which allows you to act on issues.

So please have a look and give your thoughts, thanks!

**Comment by olegKoshmeliuk** [comment]
You meed to update durable sink to respect EmitEventFailure option.
For example from your test applcation
image
it this case FailureSink will be not called and it's not clear for sink clients. 
For durable sink you can log into failure sink logevent with payload and error.
Rest is good. 👍

**Comment by mivano** [comment]
Thanks for the review. I will make the changes and do a PR.

**Comment by mivano** [comment]
See #127

**Pull request closed without merging**
