### PR TITLE
Added QueueSizeLimit to ElasticsearchSink.

### PR DESCRIPTION
**Pull request by konste**

### CODE REVIEW

**Comment by mivano** [comment]
Can you pull this against the dev branch?

**Comment by konste** [comment]
I checked that other PR and no it does not cover QueueSizeLimit,so my PR is still relevant. 

I have tried to change the base branch for my PR from serilog:master to serilog:dev, but it added whole bunch of other commits to my PR. I don't know Git well enough to sort it out.

**Comment by frg** [comment]
Is this pr dead? QueueSizeLimit is what is needed to prevent memory hogging when ElasticSearch goes down.

I can open up a new one if it :)

**Comment by mivano** [comment]
Branch is pretty old and no movement on it. The feature request is certainly valid and do see #119 
So let's see if we can implement this.

**Pull request closed without merging**
