### PR TITLE
More options in config file.

### PR DESCRIPTION
**Pull request by StevenVandenBroeck**

### CODE REVIEW

**Comment by mivano** [comment]
Thanks for the PR. Makes sense to support more parameters from the config. However, by adding them in the extension as optional parameters with default values, do you not introduce a breaking change? Would adding a new overloaded method be a better option?

**Comment by StevenVandenBroeck** [comment]
I've used the same defaults as in ElasticsearchSinkOptions, but I can change it to an overload.

**Comment by StevenVandenBroeck** [comment]
I can't make an overload because of the optional parameters (ambiguous error).

**Comment by mivano** [comment]
Ok, then we use the optional parameters. Thanks for the PR, I will merge it to dev.

**Pull request merged**
