### PR TITLE
Added option to not store rendered message

### PR DESCRIPTION
**Pull request by ipinak**

### CODE REVIEW

**Comment by mivano** [comment]
What is your use case that you want to disable this option? You can also implement this now by using your custom formatter instead?

**Comment by ipinak** [comment]
I've used this 

```
"WriteTo": [
      {
        "Name": "ColoredConsole",
        "Args": {
          "outputTemplate": "{Timestamp:yyyy-MM-dd HH:mm:ss.fff} [{Level}] {Message}{NewLine}{Exception}"
        }
      }
    ]
```
But it seems that it logs `message` twice.

**Comment by mivano** [comment]
What you show here is the output template for a colored console sink, not the ES one. 

If you want to change the output, use a customer formatter. Your change here is a breaking one as it impact signature even while it is optional.

**Comment by mivano** [comment]
Still missing the reason why you want this change? Closing for now.

**Comment by ipinak** [comment]
Sorry, for not replying. Close it.

**Pull request closed without merging**
