### PR TITLE
Add support for number_of_replicas

### PR DESCRIPTION
**Pull request by jackstu**

### CODE REVIEW

**Comment by mivano** [comment]
That is a nice addition. Thanks!

**Comment by jackstu** [comment]
Thanks. When are you planning to upload a new version to nuget?

**Comment by mivano** [comment]
Sorry @jackstu for the late reply. There is some other PR in progress for converting the project file. I m a bit waiting to combine these two. Are you in need for this feature?

**Comment by jackstu** [comment]
No problem @mivano. I've created workaround in my project so no big need.

**Comment by mivano** [comment]
Will be in 5.2, thanks.

**Pull request merged**
