### PR TITLE
templateCustomSettings loaded from settings.json file

### PR DESCRIPTION
**Pull request by tresoldigiorgio**
**Does this PR introduce a breaking change?**
NO

**Other information**:
added templateCustomSettings to sink constructor for configurations loaded from settings.json file

### CODE REVIEW

**Comment by tresoldigiorgio** [comment]
I don't know if this is the correct way to do a second PR. I don't understand why it takes the commits that I had already merged

**Comment by mivano** [comment]
Somewhat confusing PR as it contains code that is already merged. I understand that you want to add the dictionary of optional settings for the template to the ES function? What is the reason to specify it like this? To use it in the appconfig?

**Comment by tresoldigiorgio** [comment]
Yes. I use the "appsettings.json" file to configure serilog. this is my example configuration: 
`{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Elasticsearch"
    ],
    "WriteTo": [
      {
        "Name" : "Elasticsearch",
        "Args" : {
            "nodeUris" : "http://localhost:9200",
            "indexFormat" : "test-fields",
            "overwriteTemplate": true,
            "autoRegisterTemplate": true,
            "autoRegisterTemplateVersion": 2,
            "numberOfShards" : 1,
            "numberOfReplicas" : 0,
            "templateCustomSettings": {
              "index.mapping.total_fields.limit": "10000000"
            }
        }
      }
    ],
    "Enrich": [
      "FromLogContext",
      "WithMachineName",
      "WithExceptionDetails",
      "WithThreadId"
    ],
    "Properties": {
      "Application": "AppName"
    }
  }
}`

**Comment by mivano** [comment]
Merged to dev, updated readme.md file as well. Please try the alpha package and see if this suits your needs.

**Pull request merged**
