### PR TITLE
Update rolling file/file/serilog package dependencies

### LINKED ISSUE #66: Issues with durable sink after upgrade to current stable version
Hi,
I've just upgraded from an older version (of serilog and the elasticsearch sink) and whenever i try to use the durable sink I get an "System.MissingMethodException" in "Serilog.Sinks.Elasticsearch.dll"

Method not found: "Void Serilog.Sinks.RollingFile.RollingFileSink..ctor(System.String, Serilog.Formatting.ITextFormatter, System.Nullable`1<Int64>, System.Nullable`1<Int32>, System.Text.Encoding, Boolean)".

As soon as i remove the BufferBaseFilename from the elasticsearchOptions i do no longer get an exception - but of course i'm loosing the durability :(

` var elasticSearchOptions = new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
                                           {
                                               AutoRegisterTemplate = true,
                                               IndexFormat = "some-app-{0:yyyy.MM.dd}",
                                               BufferBaseFilename = @"e:\some-app-buffer.log",
                                               BatchPostingLimit = 10000,
                                               MinimumLogEventLevel = LogEventLevel.Information
                                           };
            Logger = new LoggerConfiguration().WriteTo.Elasticsearch(elasticSearchOptions).CreateLogger();`

Regards,
Jan

### PR DESCRIPTION
**Pull request by nblumhardt**
These have moved forward a little, and in the case of `RollingFile` a binary breaking change was introduced. Fixes #66.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Looks like I need to refresh my working copy, a couple of redundant history entries in there. "Squash and merge" should get rid of them :-)

**Comment by mookid8000** [comment]
Anyone care to merge this one?

**Comment by mivano** [comment]
Done, tx

**Comment by mookid8000** [comment]
Excellent 😎

**Pull request merged**
