### PR TITLE
Add support for number_of_shards

### PR DESCRIPTION
**Pull request by koenmetsu**

### CODE REVIEW

**Comment by CumpsD** [comment]
Would be a nice change! This would lower our memory pressure since we are now using loads of shards with the default settings.

Looking forward to this to be merged

**Comment by mivano** [comment]
Nice addition. Thanks!

**Comment by koenmetsu** [comment]
Thanks. Any idea when you'll be releasing the new package to nuget?

**Comment by mivano** [comment]
Should be available now as 5.1.0

**Comment by CumpsD** [comment]
Thanks

**Pull request merged**
