### PR TITLE
Format stacktrace as array

### LINKED ISSUE #232: Bug in stack trace as array of strings
https://github.com/serilog/serilog-sinks-elasticsearch/blob/f9f80778c743ea2f1d8c7eb008f171a6ed59ad28/src/Serilog.Formatting.Elasticsearch/ExceptionAsObjectJsonFormatter.cs#L54

The formatStackTraceAsArray parameter is passed to the base classes renderMessageTemplate parameter

### PR DESCRIPTION
**Pull request by oscarmorasu**
**What issue does this PR address?**
Fix #232

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x ] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [ ] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by mivano** [comment]
Looks like there is a merge conflict. Can you resolve that one?

**Comment by mivano** [comment]
I think your branch contains more commits than your intended change.

**Comment by oscarmorasu** [comment]
Sorry about that @mivano I hadn't merged the dev branch into mine

**Comment by vhatsura** [comment]
It's also would be nice to correct comments for ElasticsearchJsonFormatter constructor

image

**Comment by oscarmorasu** [comment]
@vhatsura , @mivano let me know if you see any other issues with this PR

**Comment by mivano** [comment]
The Serilog.Sinks.Elasticsearch.7.2.0-alpha0004 package should contain this latest code. Let me know if this was sufficient, then I can create the final package from master.

**Pull request merged**
