### PR TITLE
Replaced DynamicResponse with generic response type. DynamicResponse …

### PR DESCRIPTION
**Pull request by konste**
…or BulkResponse may be used.

### CODE REVIEW

**Comment by konste** [comment]
Phew!
@Mpdreamz, @mivano please pull it - I need this change the sooner the better.

**Comment by mivano** [comment]
Done!

**Comment by konste** [comment]
Thank you!

**Comment by mivano** [comment]
If you can have a look at #32 for me and give your feedback, then we can get rid of that .net 4 too.

**Comment by konste** [comment]
Yes, I'm looking with the great enjoyment. Will respond there.

**Comment by Mpdreamz** [comment]
This LGTM it might be better though to ship this sink with a mapping of the bulk response over making the method generic. 

Will sent a PR tomorrow

**Comment by konste** [comment]
Ok, I will hold off using current version until I see your variant.

**Pull request merged**
