### PR TITLE
Ship formatters in separate nuget package

### PR DESCRIPTION
**Pull request by vhatsura**
**What issue does this PR address?**
#176 

**Does this PR introduce a breaking change?**
No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [x] Unit Tests for the changes have been added (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by mivano** [comment]
Thanks for the PR. Looks good, but just one question and that might just be my lack of Nuget knowledge; should the `Serilog.Sinks.Elasticsearch.nuspec` file not need a reference to the newly created nuget formatter package? 

Next to that; can you also update the readme.md file with some details?

Thanks!

**Comment by vhatsura** [comment]
@mivano, you're right regarding `nuspec` file, however, packages are packed by `dotnet pack` command, which is clever and understand that `Serilog.Formatting.Elasticsearch` should be added to dependency graph inside `nuspec` file. You can check it by yourself from generated nuget package in AppVeyor.

Regarding `Readme.md`, I'll do it, but could clarify which info you want to see, please?

**Comment by mivano** [comment]
Thanks! I do indeed see the nuget packages referenced when looking in NuGet Explorer. I merged to dev and will prepare a final package.

**Comment by vhatsura** [comment]
Got it, thanks. I started to write some details regarding new package. If it possible, it would be good wait changes before final package will be  released.

**Comment by mivano** [comment]
Looks like the master build was skipped due to some condition. I will await your changes and will try again with those details.

**Pull request merged**
